# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  docker-install-client:
    docker:
      - image: circleci/node:12.13.0
jobs:
  client_linter:
    executor: docker-install-client
    steps:
      - checkout
      # Download dans cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: lint
          command: npm run lint
  client_deploy:
    executor: docker-install-client
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Chmod
          command: chmod +x ./scripts/deploy.sh
      - run:
          name: Deploy
          command: ./scripts/deploy.sh dist

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - client_linter
      - client_deploy:
          requires:
            - client_linter
          filters:
            branches:
              only: master
