name: Client

on:
  pull_request:

  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  lint:
    name: client-linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.13
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-
      - name: Install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: lint
    name: client-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.13
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1-npm-deps-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Move files
        run: mv ./src/pages/sitemap.txt ./dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: magsout.com
